// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/racker/rackspace-monitoring-poller/check (interfaces: Pinger)

package check_test

import (
	gomock "github.com/golang/mock/gomock"
	check "github.com/racker/rackspace-monitoring-poller/check"
)

// Mock of Pinger interface
type MockPinger struct {
	ctrl     *gomock.Controller
	recorder *_MockPingerRecorder
}

// Recorder for MockPinger (not exported)
type _MockPingerRecorder struct {
	mock *MockPinger
}

func NewMockPinger(ctrl *gomock.Controller) *MockPinger {
	mock := &MockPinger{ctrl: ctrl}
	mock.recorder = &_MockPingerRecorder{mock}
	return mock
}

func (_m *MockPinger) EXPECT() *_MockPingerRecorder {
	return _m.recorder
}

func (_m *MockPinger) Ping(_param0 int) <-chan *check.PingResponse {
	ret := _m.ctrl.Call(_m, "Ping", _param0)
	ret0, _ := ret[0].(<-chan *check.PingResponse)
	return ret0
}

func (_mr *_MockPingerRecorder) Ping(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Ping", arg0)
}
