language: go

sudo: false


go:
  - 1.7.x

install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout v0.12.3 && go install && cd -
  - glide install

script:
  - go test $(glide novendor)
