language: go

sudo: false

go:
  - 1.8.3

install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout v0.12.3 && go install && cd -
  - go get -v github.com/mitchellh/gox
  - cd $GOPATH/src/github.com/mitchellh/gox && git checkout v0.3.0 && go install && cd -
  - glide install
  - gem install --no-ri --no-rdoc fpm

script:
  - go test -short -v $(glide novendor)
  - CGO_ENABLED=0 gox
    -osarch "linux/386 linux/amd64 darwin/amd64"
    -output="build/{{.Dir}}_{{.OS}}_{{.Arch}}"
    -ldflags="-X github.com/racker/rackspace-monitoring-poller/version.Version=$(git symbolic-ref -q --short HEAD || git describe --tags --exact-match)"
  # integration tests need the latest rackspace-monitoring-poller built
  - go test -v github.com/racker/rackspace-monitoring-poller/integrationcli
  - make package-deb-local
after_script:
  - go get github.com/mattn/goveralls
  - bash contrib/combine-coverage.sh --coveralls
deploy:
  provider: releases
  # Generate OAuth token at https://github.com/settings/tokens and configure in
  # project settings https://travis-ci.org/racker/rackspace-monitoring-poller/settings
  api_key: "$GITHUB_OAUTH_TOKEN"
  file_glob: true
  file:
    - "build/rackspace-monitoring-poller_*"
  skip_cleanup: true
  on:
    tags: true
