language: go
sudo: false
go:
- 1.9.1
install:
- make install-fpm
script:
- make test build test-integrationcli package-deb-local
after_script:
- make coverage
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file_glob: true
  file:
  - build/rackspace-monitoring-poller_*
  skip_cleanup: true
  on:
    tags: true
notifications:
  slack:
    secure: oj8QJhx7xFCNN8WFO89GeNTI9BP7A0IKP/RYg52dzugLaWzhtyInPAFZrXQaxBN8IB41VRu45gBKYGklfz90Z05MGtrFnOlsEqo52R4YIvj4UuxoVrTcuPKeWgnJ6Vm9mvxut9Dy6eej9coUOBIkTLvPoLqqM8IugpneK88PbnCkFwc2ir59x3obKjI2gXrjn8MUFnOOJFm17z9IpzBpFpVdAZkoVFJ/57MyfO6HSyloTtvbEYCephViI8lPceeWYcBeXRkf6uKqyNReYTDql7bbZDGxNyZbaqjS0OTmIOXbDIU+funA7hwDt2fXfMiGw/BX21cWYAZgLLONdvPbahbsY3D00QnE7K227s5e2mw92i+u8YN9ms/WUl8H+zAF7eJBPQnzArqciHtUxXKTpTb5KamanqeUuTHi3m8D94UZY+Fi6zihUMUIUyxqpm8UaqgCMUrYRJgTX/hrIUgFtQ3KMadkGCfGWbHJ6Xx2jQ+OAIhCM6iYfHvkkA7uOzcsjAK9VSf1tVW0muNRADG8N9OmYzhHtPcJQ0Z29U8D8iMd1cmSp0mJWRSqr9o9cf8gspfAtrKMHBlsRAtYtjli98adK64x21t8Nhqk00rYnLwArGVA9eyar6r0MKrAvN2shEZoyuZcVO9I1YYt0f43nQTRYgL7qq/BMPflfjtOr3A=
