language: go

sudo: false

matrix:
  include:
    - go: 1.7.3

install:
  - go get -u -v $(go list -f '{{join .Imports "\n"}}' ./... | sort | uniq | grep -v golang-samples)

script:
  - go test -v ./...;
