# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.synced_folder "../../build", "/packages"

  config.vm.define "14_04" do |m|
    m.vm.box = "ubuntu/trusty64"
    m.vm.provision "shell", path: "provision.sh"
  end

  config.vm.define "16_04" do |m|
    m.vm.box = "ubuntu/xenial64"
    m.vm.provision "shell", path: "provision.sh"
  end

  config.vm.define "18_04" do |m|
    m.vm.box = "ubuntu/bionic64"
    m.vm.provision "shell", path: "provision.sh"
  end

  config.vm.define "centos7" do |m|
    m.vm.box = "geerlingguy/centos7"
  end

end
